# Generated by Django 4.2.2 on 2023-06-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('numero_registro', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('puesto_institucional', models.CharField(max_length=255)),
                ('unidad_pertenece', models.CharField(max_length=255)),
                ('direccion_institucional', models.CharField(max_length=255)),
                ('ciudad_labora', models.CharField(max_length=255)),
                ('telefono_institucional', models.CharField(max_length=255)),
                ('extension_telefonica', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
    ]
